# Generated by Django 3.2.7 on 2022-07-24 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SNS_App', '0038_auto_20220724_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='finished_book',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reserved_book',
        ),
        migrations.CreateModel(
            name='ReserveRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNS_App.bookdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinishRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SNS_App.bookdata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='finished_books',
            field=models.ManyToManyField(related_name='finished_books', through='SNS_App.FinishRegistration', to='SNS_App.BookData'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reserved_books',
            field=models.ManyToManyField(related_name='reserved_books', through='SNS_App.ReserveRegistration', to='SNS_App.BookData'),
        ),
    ]
