from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('',SignupView.as_view(),name='signup'),
    path('login/',login_func,name='login'),
    path('logout/',logout_func,name='logout'),
    path('authenticate-for-email-change/',authenticate_for_email_change,name='AuthenticateForEmailChange'),
    path('email-change/<str:token>/',email_change,name='EmailChange'),
    path('email-change/<str:token>/done/',email_change_done,name='EmailChangeDone'),
    path('password-change/',password_change,name='PasswordChange'),
    path('password-change/done/',passeword_change_done,name='PasswordChangeDone'),
    path('password-reset/',password_reset,name='PasswordReset'),
    path('password-reset/done/',password_reset_done,name='PasswordResetDone'),
    path('password-reset-confirm/<str:uidb64>/<str:token>/',password_reset_confirm,name='PasswordResetConfirm'),
    path('password-reset-complete/',password_reset_complete,name='PasswordResetComplete'),
    path('home/',HomeView.as_view(),name='home'),
    path('home2/',Home2View.as_view(),name='home2'),
    path('tweet-create/<str:ISBNcode>',tweet_create,name='tweetCreate'),
    path('select-item/<str:ISBNcode>',select_item,name='SelectItem'), 
    path('tweet-delete/<int:tweet_pk>',tweet_del,name='TweetDelete'),
    path('comment-delete/<int:comment_pk>',comment_del,name='CommentDelete'),
    path('profile-edit/<int:pk>',profile_editView.as_view(),name='profile_edit'),
    path('search-user/',SearchUserView.as_view(),name='search_user'),
    path('follower/<int:user_id>/',follower_show,name='follower'),
    path('following/<int:user_id>/',following_show,name='following'),
    path('tweet-like/',tweet_like_func, name='tweet_like'),
    path('comment-like/',comment_like_func, name='comment_like'),
    path('register-reserved-book/',register_reserved_book, name='RegisterReserveBook'),
    path('register-finished-book/',register_finished_book, name='RegisterFinishedBook'),
    path('user-page-at-home/<int:pk>/',UserPageAtHomeView.as_view(), name='UserPageAtHome'),
    path('user-page-at-reserved-book/<int:pk>/',UserPageAtReservedBookView.as_view(), name='UserPageAtReservedBook'),
    path('user-page-at-finished-book/<int:pk>/',UserPageAtFinishedBookView.as_view(), name='UserPageAtFinishedBook'),
    path('follow/',follow_func, name='follow'),
    path('create-comment/<int:tweet_pk>',create_comment, name='CreateComment'),
    path('chat/<int:user_id>', Chat.as_view(), name='Chat'),
    path('chat-room/<uuid:room_id>', chat_room, name='chat_room'),
    path('room/<int:pk>', room, name='room'),
    path('search-item/<str:From>',SearchItem.as_view(),name='SearchItem'),
    path('tweet-of-item/<str:ISBNcode>',TweetOfItemView.as_view(),name='TweetOfItem'),
]
